services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT}:9001"
    volumes:
        - stuart-db:/usr/src/app/db/
      
volumes:
  stuart-db:
